## Dataset link:
[Kaggle](https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database)

In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("/content/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
X.shape

(768, 8)

In [9]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [10]:
y.shape

(768,)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [12]:
X = scaler.fit_transform(X)

In [13]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [16]:
import tensorflow as tf

In [17]:
LAYERS = [
    tf.keras.layers.Dense(32, activation='relu', input_dim = 8),
    tf.keras.layers.Dense(1, activation='sigmoid')
]

model = tf.keras.models.Sequential(LAYERS)

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321 (1.25 KB)
Trainable params: 321 (1.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
LOSS_FUNCTION = 'binary_crossentropy'
OPTIMIZER = 'Adam'
METRICS = ['accuracy']

model.compile(loss= LOSS_FUNCTION,
              optimizer= OPTIMIZER,
              metrics= METRICS)

In [20]:
model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
20/20 [==============================] - 2s 20ms/step - loss: 0.8086 - accuracy: 0.3664 - val_loss: 0.7272 - val_accuracy: 0.4610
Epoch 2/10
20/20 [==============================] - 0s 4ms/step - loss: 0.7013 - accuracy: 0.5016 - val_loss: 0.6459 - val_accuracy: 0.6558
Epoch 3/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6276 - accuracy: 0.7052 - val_loss: 0.5968 - val_accuracy: 0.7208
Epoch 4/10
20/20 [==============================] - 0s 4ms/step - loss: 0.5772 - accuracy: 0.7573 - val_loss: 0.5653 - val_accuracy: 0.7532
Epoch 5/10
20/20 [==============================] - 0s 4ms/step - loss: 0.5432 - accuracy: 0.7736 - val_loss: 0.5441 - val_accuracy: 0.7662
Epoch 6/10
20/20 [==============================] - 0s 4ms/step - loss: 0.5199 - accuracy: 0.7769 - val_loss: 0.5311 - val_accuracy: 0.7662
Epoch 7/10
20/20 [==============================] - 0s 4ms/step - loss: 0.5018 - accuracy: 0.7866 - val_loss: 0.5230 - val_accuracy: 0.7532
Epoch 8/10
20/20 [=

## Agenda:
1. How to select best Optimizer
2. How to select no. of nodes/neurons in a layers
3. How to select no. of layers
4. All in one model

In [21]:
!pip install -U keras-tuner

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 1.6 MB/s eta 0:00:00


In [22]:
import keras_tuner as kt

### 1. How to select best Optimizer

In [23]:
def build_model(hp):

  LAYERS = [
    tf.keras.layers.Dense(32, activation='relu', input_dim = 8),
    tf.keras.layers.Dense(1, activation='sigmoid')
    ]

  model = tf.keras.models.Sequential(LAYERS)


  LOSS_FUNCTION = 'binary_crossentropy'
  OPTIMIZER = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])
  METRICS = ['accuracy']

  model.compile(loss= LOSS_FUNCTION,
                optimizer= OPTIMIZER,
                metrics= METRICS)

  return model

In [24]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 5)

In [25]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 10s


In [26]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [27]:
model = tuner.get_best_models(num_models=1)[0]

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321 (1.25 KB)
Trainable params: 321 (1.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [29]:
model.fit(X_train, y_train, epochs=10, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/10
20/20 [==============================] - 1s 13ms/step - loss: 0.5464 - accuracy: 0.7622 - val_loss: 0.5399 - val_accuracy: 0.7857
Epoch 8/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5247 - accuracy: 0.7655 - val_loss: 0.5232 - val_accuracy: 0.7857
Epoch 9/10
20/20 [==============================] - 0s 4ms/step - loss: 0.5072 - accuracy: 0.7622 - val_loss: 0.5098 - val_accuracy: 0.7987
Epoch 10/10
20/20 [==============================] - 0s 4ms/step - loss: 0.4936 - accuracy: 0.7704 - val_loss: 0.5011 - val_accuracy: 0.7857


## 2. How to select no. of nodes/neurons in a layers

In [30]:
def build_model(hp):

  units = hp.Int('units', min_value = 8, max_value = 128, step=8)

  LAYERS = [
    tf.keras.layers.Dense(units= units, activation='relu', input_dim = 8),
    tf.keras.layers.Dense(1, activation='sigmoid')
    ]

  model = tf.keras.models.Sequential(LAYERS)


  LOSS_FUNCTION = 'binary_crossentropy'
  OPTIMIZER = 'rmsprop'
  METRICS = ['accuracy']

  model.compile(loss= LOSS_FUNCTION,
                optimizer= OPTIMIZER,
                metrics= METRICS)

  return model

In [31]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 5,
                        directory='mydir')

In [32]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7337662577629089

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 11s


In [33]:
tuner.get_best_hyperparameters()[0].values

{'units': 112}

### 3. How to select no. of layers

In [34]:
import tensorflow as tf
import keras
from keras.layers import Dense
from keras.models import Sequential

In [35]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(88, activation = 'relu', input_dim=8))

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(88, activation = 'relu'))

  model.add(Dense(1, activation = 'sigmoid'))

  LOSS_FUNCTION = 'binary_crossentropy'
  OPTIMIZER = 'rmsprop'
  METRICS = ['accuracy']

  model.compile(loss= LOSS_FUNCTION,
                optimizer= OPTIMIZER,
                metrics= METRICS)

  return model

In [36]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 5,
                        directory='mydir1')

In [37]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 15s


In [39]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 7}

In [40]:
model = tuner.get_best_models(num_models=1)[0]

In [41]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 88)                792       
                                                                 
 dense_1 (Dense)             (None, 88)                7832      
                                                                 
 dense_2 (Dense)             (None, 88)                7832      
                                                                 
 dense_3 (Dense)             (None, 88)                7832      
                                                                 
 dense_4 (Dense)             (None, 88)                7832      
                                                                 
 dense_5 (Dense)             (None, 88)                7832      
                                                                 
 dense_6 (Dense)             (None, 88)                7

## 4. All in one model

In [42]:
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers',min_value= 1,max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('units' + str(i),min_value= 8,max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh']),
                      input_dim=8))


    else:
      model.add(Dense(hp.Int('units' + str(i),min_value= 8,max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh'])))

    counter += 1


  model.add(Dense(1, activation='sigmoid'))


  LOSS_FUNCTION = "binary_crossentropy"
  OPTIMIZER = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])
  METRICS = ["accuracy"]

  model.compile(loss=LOSS_FUNCTION,
                optimizer=OPTIMIZER,
                metrics=METRICS)

  return model

In [43]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 5,
                        directory='mydir2')

In [44]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6688311696052551

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 12s


In [45]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 80,
 'activation0': 'tanh',
 'optimizer': 'rmsprop',
 'units1': 32,
 'activation1': 'relu',
 'units2': 24,
 'activation2': 'tanh',
 'units3': 64,
 'activation3': 'tanh',
 'units4': 72,
 'activation4': 'relu',
 'units5': 56,
 'activation5': 'relu'}

In [46]:
model = tuner.get_best_models(num_models=1)[0]

In [47]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 80)                720       
                                                                 
 dense_1 (Dense)             (None, 32)                2592      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 3345 (13.07 KB)
Trainable params: 3345 (13.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
model.fit(X_train, y_train, epochs=10, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/10
20/20 [==============================] - 1s 12ms/step - loss: 0.4855 - accuracy: 0.7638 - val_loss: 0.4893 - val_accuracy: 0.7922
Epoch 8/10
20/20 [==============================] - 0s 3ms/step - loss: 0.4596 - accuracy: 0.7769 - val_loss: 0.4926 - val_accuracy: 0.7727
Epoch 9/10
20/20 [==============================] - 0s 4ms/step - loss: 0.4492 - accuracy: 0.7818 - val_loss: 0.4969 - val_accuracy: 0.7662
Epoch 10/10
20/20 [==============================] - 0s 4ms/step - loss: 0.4417 - accuracy: 0.7964 - val_loss: 0.4919 - val_accuracy: 0.7662
